CREATE TABLE whp_reports.district (
    name varchar(100) UNIQUE NOT NULL
);

INSERT INTO whp_reports.district(name) VALUES ('Araria');
INSERT INTO whp_reports.district(name) VALUES ('Arwal');
INSERT INTO whp_reports.district(name) VALUES ('Aurangabad');
INSERT INTO whp_reports.district(name) VALUES ('Bangalore');
INSERT INTO whp_reports.district(name) VALUES ('Banka');
INSERT INTO whp_reports.district(name) VALUES ('Begusarai');
INSERT INTO whp_reports.district(name) VALUES ('Bhagalpur');
INSERT INTO whp_reports.district(name) VALUES ('Bhojpur');
INSERT INTO whp_reports.district(name) VALUES ('Buxar');
INSERT INTO whp_reports.district(name) VALUES ('Darbhanga');
INSERT INTO whp_reports.district(name) VALUES ('East Champaran');
INSERT INTO whp_reports.district(name) VALUES ('Gaya');
INSERT INTO whp_reports.district(name) VALUES ('Gopalganj');
INSERT INTO whp_reports.district(name) VALUES ('Jamui');
INSERT INTO whp_reports.district(name) VALUES ('Jehanabad');
INSERT INTO whp_reports.district(name) VALUES ('Kaimur');
INSERT INTO whp_reports.district(name) VALUES ('Katihar');
INSERT INTO whp_reports.district(name) VALUES ('Khagaria');
INSERT INTO whp_reports.district(name) VALUES ('Kishanganj');
INSERT INTO whp_reports.district(name) VALUES ('Lakhisarai');
INSERT INTO whp_reports.district(name) VALUES ('Madhepura');
INSERT INTO whp_reports.district(name) VALUES ('Madhubani');
INSERT INTO whp_reports.district(name) VALUES ('Monghyr');
INSERT INTO whp_reports.district(name) VALUES ('Muzaffarpur');
INSERT INTO whp_reports.district(name) VALUES ('Nalanda');
INSERT INTO whp_reports.district(name) VALUES ('Nawada');
INSERT INTO whp_reports.district(name) VALUES ('New Delhi');
INSERT INTO whp_reports.district(name) VALUES ('Patna');
INSERT INTO whp_reports.district(name) VALUES ('Purnea');
INSERT INTO whp_reports.district(name) VALUES ('Rohtas');
INSERT INTO whp_reports.district(name) VALUES ('Saharsa');
INSERT INTO whp_reports.district(name) VALUES ('Samastipur');
INSERT INTO whp_reports.district(name) VALUES ('Saran');
INSERT INTO whp_reports.district(name) VALUES ('Sheohar');
INSERT INTO whp_reports.district(name) VALUES ('Shiekhpura');
INSERT INTO whp_reports.district(name) VALUES ('Sitamarhi');
INSERT INTO whp_reports.district(name) VALUES ('Siwan');
INSERT INTO whp_reports.district(name) VALUES ('Supaul');
INSERT INTO whp_reports.district(name) VALUES ('TestDistrict');
INSERT INTO whp_reports.district(name) VALUES ('Vaishali');
INSERT INTO whp_reports.district(name) VALUES ('West Champaran');
