CREATE TABLE whp_reports.sputum_tracking (
    sputum_tracking_id serial NOT NULL,
    container_id varchar(100),
    date_issued_on date,
    provider_id varchar(100),
    submitter_role varchar(100),
    submitter_id varchar(100),
    location_id varchar(100),
    instance varchar(100),
    channel_id varchar(100),
    smear_test_date1 date,
    smear_test_result1 varchar(100),
    smear_test_date2 date,
    smear_test_result2 varchar(100),
    cumulative_result varchar(100),
    lab_name varchar(100),
    lab_number varchar(100),
    lab_results_captured_on timestamp,
    container_status varchar(100),
    reason_for_closure varchar(100),
    diagnosis varchar(100),
    alternate_diagnosis_code varchar(100),
    closure_date timestamp,
    patient_id varchar(100),
    tb_id varchar(100),
    consultation_date date,
    mapping_instance varchar(100)
);
