CREATE TABLE whp_reports.sputum_tracking (
    sputum_tracking_id serial NOT NULL,
    container_id varchar(20),
    date_issued_on date,
    provider_id varchar(20),
    submitter_role varchar(10),
    submitter_id varchar(20),
    location_id varchar(20),
    instance varchar(20),
    channel_id varchar(3),
    smear_test_date1 date,
    smear_test_result1 varchar(20),
    smear_test_date2 date,
    smear_test_result2 varchar(20),
    cumulative_result varchar(20),
    lab_name varchar(100),
    lab_number varchar(20),
    lab_results_captured_on date,
    container_status varchar(20),
    reason_for_closure varchar(60),
    diagnosis varchar(20),
    alternate_diagnosis_code varchar(20),
    closure_date date,
    patient_id varchar(20),
    tb_id varchar(20),
    consultation_date date,
    mapping_instance varchar(20)
);
